/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef GPSDFIX_H
#define GPSDFIX_H

/* function declarations */
void init_gpsdFix(void);
Netsnmp_Node_Handler handle_gpsdFixTime;
Netsnmp_Node_Handler handle_gpsdFixMode;
Netsnmp_Node_Handler handle_gpsdFixEpt;
Netsnmp_Node_Handler handle_gpsdFixLatitude;
Netsnmp_Node_Handler handle_gpsdFixEpy;
Netsnmp_Node_Handler handle_gpsdFixLongitude;
Netsnmp_Node_Handler handle_gpsdFixEpx;
Netsnmp_Node_Handler handle_gpsdFixAltitude;
Netsnmp_Node_Handler handle_gpsdFixEpv;
Netsnmp_Node_Handler handle_gpsdFixTrack;
Netsnmp_Node_Handler handle_gpsdFixEpd;
Netsnmp_Node_Handler handle_gpsdFixSpeed;
Netsnmp_Node_Handler handle_gpsdFixEps;
Netsnmp_Node_Handler handle_gpsdFixClimb;
Netsnmp_Node_Handler handle_gpsdFixEpc;

#endif /* GPSDFIX_H */
